name: Deploy Python App to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: |
        docker build -t my-python-app .

    - name: Save Docker Image
      run: |
        docker save my-python-app | gzip > my-python-app.tar.gz

    - name: Copy Image to VPS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "my-python-app.tar.gz"
        target: "/home/${{ secrets.VPS_USER }}/"

    - name: Deploy on VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          docker stop my-python-app || true
          docker rm my-python-app || true
          docker load < /home/${{ secrets.VPS_USER }}/my-python-app.tar.gz
          docker run -d --restart unless-stopped --name my-python-app -p 80:8000 my-python-app
          rm /home/${{ secrets.VPS_USER }}/my-python-app.tar.gz

